name: Deploy to production

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DISCORD_CLIENT_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DISCORD_CLIENT_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-southeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Cache modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region ap-southeast-1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Set Env
        run: echo $'DATABASE_URL=$DATABASE_URL\nNEXTAUTH_SECRET=$NEXTAUTH_SECRET\nNEXTAUTH_URL=$NEXTAUTH_URL\nDISCORD_CLIENT_ID=$DISCORD_CLIENT_ID\nDISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET\nS3_UPLOAD_KEY=$S3_UPLOAD_KEY\nS3_UPLOAD_SECRET=$S3_UPLOAD_SECRET\nS3_UPLOAD_BUCKET=$S3_UPLOAD_BUCKET\nS3_UPLOAD_REGION=$S3_UPLOAD_REGION\nNEXT_PUBLIC_CLOUDFRONT_URL=$NEXT_PUBLIC_CLOUDFRONT_URL\nNODE_ENV=$NODE_ENV' > .env
      - name: Deploy
        run: yarn ss